sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}  

script:
  - docker images
  - export REPO=$DOCKER_USERNAME/$DOCKER_REPO 
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker run $REPO /bin/sh -c "python -V && pip --version && node -v && npm -v && yarn -V"
  - docker tag $REPO:$COMMIT $REPO:$TAG;
  - docker push $REPO;
  - docker images;
